version: '3.8'

services:

  app:
    image: ghcr.io/hcamposxx/api-laravel:latest
    container_name: api_laravel
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_DATABASE: api_crud
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: api_laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: api_crud
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
